# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1


jobs:
  createDockerImg:
    docker:
      - image: cimg/node:14.17.0
    steps:
      - run:
          name: "semantic versioning"
          command: |
            npx semantic-release --debug --no-ci


workflows:
  version: 2
  build-deploy:
    jobs:
      - createDockerImg

