# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@7.3.0

workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: 921312901458.dkr.ecr.ap-southeast-2.amazonaws.com
          aws-access-key-id: ${ACCESS_KEY_ID_ENV_VAR_NAME)
          aws-secret-access-key: ${SECRET_ACCESS_KEY_ENV_VAR_NAME}
          create-repo: true
          dockerfile: Dockerfile
          no-output-timeout: 20m
          profile-name: nodejs
          region: ap-southeast-2
          repo: myECRRepository
          skip-when-tags-exist: false
          tag: 'latest,myECRRepoTag'
